---
title: "Untitled"
author: "Simon Hansen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
# The following is to test the choropleth map plots.
## I have only tried to plot it using ggplotly - and it is SLOW!!
## We should probably try to get the size of the dataframe down some way (its 2.3 gb currently). 
## Further, we should try to make it into a truly plotly-map with added traces. 

# First we load the tidyverse
suppressPackageStartupMessages(library(tidyverse))
# Here I define the url to get data from DAWA/DAGI for landsdele. I define that the format should be geojson
url = "https://api.dataforsyningen.dk/landsdele?format=geojson"

# I will download the geojson to a temporary file
geofile = tempfile()
download.file(url, geofile)

# Then I use the rgdal package to read in the downloaded file
geodata <- rgdal::readOGR(geofile)

# Convert it to a format ggplot can read
ggplotdata = sf::st_as_sf(geodata)


#Load property data (Only one year to test) and join it with geodata
landsdel_ejendomme <- readr::read_csv("C:/Users/simon/Downloads/landsdel_ejendomme.csv", 
    col_names = FALSE, locale = locale(encoding = "ISO-8859-1"), 
    skip = 6)
landsdel_ejendomme1 <- 
  landsdel_ejendomme%>%
  dplyr::select(3,4)%>%
  dplyr::rename("Landsdele" = X3, "Indeks" = X4)%>%
  dplyr::mutate(Landsdele = stringr::str_remove_all(Landsdele, "Landsdel "))%>%
  dplyr::filter(Landsdele != "Hele landet")%>%
  dplyr::full_join(., y=ggplotdata1,by=join_by(Landsdele == navn))


#Plot the choropleth map
s<-ggplot(landsdel_ejendomme1, 
          aes(fill = Indeks, 
              geometry = geometry)) +
  geom_sf() +
  theme_void() +
  labs(title="Developments in property prices",
       subtitle = "Subtitle")  +
  theme(
    plot.title = element_text(size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    plot.caption = element_text(size = 8, hjust = 1)) +
  coord_fixed(ratio = 1.3)

ss<-ggplotly(s)
ss
```



```{r fig.height=12, fig.width=11}
#Now I do the same, but with all years (and quarters) ranging from 1992-2023
landsdel_ejendomme_alle_aar <- readr::read_delim("C:/Users/simon/Downloads/landsdel_ejendomme_alle_aar.csv", 
    delim = ";", escape_double = FALSE, col_names = FALSE, 
    trim_ws = TRUE)


#Manipulate data and join it with geodata
landsdel_ejendomme_alle_aar1 <- 
  landsdel_ejendomme_alle_aar%>%
  dplyr::rename("Aar" = X1, 
                "Hele landet" = X2,
                "Byen København" = X3,
                "Københavns omegn"= X4,
                "Nordsjælland" = X5,
                "Bornholm" = X6,
                "Østsjælland" = X7,
                "Vest- og Sydsjælland" = X8,
                "Fyn" = X9,
                "Sydjylland" = X10,
                "Østjylland" = X11,
                "Vestjylland" = X12,
                "Nordjylland" = X13)%>%
  tidyr::pivot_longer(!Aar, names_to = "Landsdele", values_to = "Indeks")%>%
  dplyr::filter(Landsdele != "Hele landet")%>%
  dplyr::full_join(., y=ggplotdata1,by=join_by(Landsdele == navn))
  
#Plot the data
s<-ggplot(landsdel_ejendomme1, 
          aes(fill = Indeks, 
              geometry = geometry,
              text = paste0(Landsdele,"\nIndeks: ", Indeks))) +
  geom_sf() +
  theme(legend.position = "bottom",
        legend.key.height = unit(x = 0.4,"line"))

  theme_void() +
  labs(title="Developments in property prices",
       subtitle = "Subtitle")  +
  theme(
    legend.position = "bottom", 
    plot.title = element_text(size = 12, hjust = 0.5),
    plot.subtitle = element_text(size = 10, hjust = 0.5),
    plot.caption = element_text(size = 8, hjust = 1)) +
  coord_fixed(ratio = 1.3)

ss<-ggplotly(s, tooltip = "text") +
  theme(legend.position = "bottom",
        legend.key.height = unit(x = 0.4,"line"))
ss
```


```{r}
p1 <- plot_ly(data = landsdel_ejendomme1, )
```

